SCREEN_WIDTH = 800
SCREEN_HEIGHT = 450  # Aspect ratio: 16:9
SCREEN_UPDATE_TIME = 0.1  # Measured in seconds
SCREEN_BACKGROUND_COLOR = "white"

TURTLE_DEFAULT_WIDTH = 20
TURTLE_DEFAULT_HEIGHT = 20

TURTLE_HEADING = 90
TURTLE_SHAPE = "turtle"
TURTLE_COLOR = "black"
TURTLE_WIDTH = 20
TURTLE_HEIGHT = 20
TURTLE_WIDTH_FACTOR = TURTLE_WIDTH / TURTLE_DEFAULT_WIDTH
TURTLE_HEIGHT_FACTOR = TURTLE_HEIGHT / TURTLE_DEFAULT_HEIGHT
TURTLE_STARTING_POSITION = (0, -(SCREEN_HEIGHT - TURTLE_HEIGHT) * 0.48)
TURTLE_MOVING_DISTANCE = 10
TURTLE_UP_KEY = "Up"
TURTLE_Y_COR_BOUNDARY = (SCREEN_HEIGHT - TURTLE_HEIGHT) * 0.48

# Score Board Constant Parameters
SCORE_BOARD_POSITION = (-0.48 * SCREEN_WIDTH, 0.44 * SCREEN_HEIGHT)
SCOREBOARD_ALIGNMENT = "left"
SCOREBOARD_FONT = ("Courier", 14, "normal")
SCOREBOARD_COLOR = "black"

CAR_HEADING = 0
CAR_SHAPE = "square"
CAR_COLORS = ["red", "orange", "yellow", "green", "blue", "purple"]
CAR_WIDTH = 20
CAR_HEIGHT = 40
CAR_WIDTH_FACTOR = CAR_WIDTH / TURTLE_DEFAULT_WIDTH
CAR_HEIGHT_FACTOR = CAR_HEIGHT / TURTLE_DEFAULT_HEIGHT
CAR_X_STARTING_POSITION = 0.5 * SCREEN_WIDTH
CAR_UPPER_Y_LIMIT = round(0.45 * SCREEN_HEIGHT) - 25
CAR_LOWER_Y_LIMIT = -CAR_UPPER_Y_LIMIT
CAR_STARTING_MOVE_SPEED = 5  # car takes 5 steps forward in level 1
CAR_MOVE_SPEED_INCREMENT = 10  # increment in number of steps taken by car as level increases
